---
title: "Untitled"
author: "Doug Barrows"
date: "11/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# annotate the UTX merged union peaks with GREAT and annotate with SE and normal enhancer overlap
```{r}
library(profileplyr)
library(rtracklayer)

UTX_K27ac_all_UTX_union_pp <- readRDS("/Users/douglasbarrows/Desktop/allis_postdoc_all_the_things/NGS_analysis_doug/20190807_UMUC1_FvS_UTXIP_ChIPseq/proplyr_K27ac_signalinUTXpeaks_groupBySE_vs_norm/proplyObject_UTX_K27ac_all_UTX_union_3kb.RData")
sampleData(UTX_K27ac_all_UTX_union_pp)$chip <- c(rep("UTX", 6), rep("K27ac", 6))

UTX_K27ac_all_UTX_union_pp_anno <- annotateRanges_great(UTX_K27ac_all_UTX_union_pp, species = "hg19")

all_enh <- import("~/Desktop/allis_postdoc_all_the_things/NGS_analysis_doug/ChIPseq_pipeline_FullVsSphereK27ac_UTX_MNase_20190328/beds_removeblacklist/K27ac_K4me1_overlap_EV_WT_HEAA_union_inclProm.bed")

UTX_K27ac_all_UTX_union_pp_anno <- groupBy(UTX_K27ac_all_UTX_union_pp_anno,
                                           all_enh,
                                           GRanges_names = "all_enh",
                                           include_nonoverlapping = TRUE)

```




# get the genes that change significantly up or down in EV sphere vs EV full

```{r}
library(DESeq2)
library(tidyr)
dds_EVSvF <- readRDS("/Users/douglasbarrows/Desktop/allis_postdoc_all_the_things/NGS_analysis_doug/20190807_UMUC1_FvS_UTXIP_ChIPseq/gene_expression_enhancer_and_SE_genes/all_enh_genes/figures_for_paper/dds_EVspherevsEVfull.RData")
resultsNames(dds_EVSvF)
res_EVSvF <- results(dds_EVSvF, name = "media_sphere_vs_full")

# dds_EVSvF <- estimateSizeFactors(dds_EVSvF)
# counts_EVSvF <- counts(dds_EVSvF, normalized=T)
# 
# counts_EVSvF_norm_df <- data.frame(counts_EVSvF)

library(org.Hs.eg.db)
geneIDs <- substr(rownames(dds_EVSvF), 1, 15)
gene_symbols <- mapIds(org.Hs.eg.db, keys = geneIDs, column = "SYMBOL", keytype = "ENSEMBL", multiVals = "first")
res_EVSvF$GeneName <- gene_symbols

res_EVSvF <- na.omit(res_EVSvF)

EVSvF_UPgenes_FC205 <- res_EVSvF[res_EVSvF$log2FoldChange > 1 & res_EVSvF$padj < 0.05, 7] %>%
  unname() 


EVSvF_DOWNgenes_FC205 <- res_EVSvF[res_EVSvF$log2FoldChange < -1 & res_EVSvF$padj < 0.05, 7] %>% 
  unname()

genes_up_or_down <- list(EVSvF_UPgenes_FC205, EVSvF_DOWNgenes_FC205)
names(genes_up_or_down) <- c("EVSvF_UPgenes_FC205", "EVSvF_DOWNgenes_FC205")
```

# annotate ranges with overlap with these gene lists 

```{r}

UTX_K27ac_all_UTX_union_pp_anno <- groupBy(UTX_K27ac_all_UTX_union_pp_anno,
                                           group = genes_up_or_down,
                                           include_nonoverlapping = TRUE)

table(mcols(UTX_K27ac_all_UTX_union_pp_anno)$GL_overlap_names)

UTX_K27ac_all_UTX_union_pp_anno_groupUPdown <- groupBy(UTX_K27ac_all_UTX_union_pp_anno,
                                           group = "GL_overlap_names")


```

#ALL ENHANCER OVERLAP  - get the genes that overlap UTX peaks and enhancer peak

```{r}

UPinSphere_AllEnhOverlap <- mcols(UTX_K27ac_all_UTX_union_pp_anno)[(mcols(UTX_K27ac_all_UTX_union_pp_anno)$GR_overlap_names %in% "all_enh" & mcols(UTX_K27ac_all_UTX_union_pp_anno)$GL_overlap_names %in% "EVSvF_UPgenes_FC205"), 6] %>%
  unique()

DOWNinSphere_AllEnhOverlap <- mcols(UTX_K27ac_all_UTX_union_pp_anno)[(mcols(UTX_K27ac_all_UTX_union_pp_anno)$GR_overlap_names %in% "all_enh" & mcols(UTX_K27ac_all_UTX_union_pp_anno)$GL_overlap_names %in% "EVSvF_DOWNgenes_FC205"), 6] %>%
  unique()
```

```{r}

library(DESeq2)
dds_allsamples <- readRDS("/Users/douglasbarrows/Desktop/allis_postdoc_all_the_things/NGS_analysis_doug/20190807_UMUC1_FvS_UTXIP_ChIPseq/gene_expression_enhancer_and_SE_genes/allsamples_ddsobject_fullandsphere.RData")
dds_allsamples <- estimateSizeFactors(dds_allsamples)
counts_all_samples <- counts(dds_allsamples, normalized=T)

counts_all_samples_norm_df <- data.frame(counts_all_samples)

library(org.Hs.eg.db)
geneIDs <- substr(rownames(counts_all_samples_norm_df), 1, 15)
gene_symbols <- mapIds(org.Hs.eg.db, keys = geneIDs, column = "SYMBOL", keytype = "ENSEMBL", multiVals = "first")
counts_all_samples_norm_df$GeneName <- gene_symbols

EV_full_mean <- data.frame(GeneName = counts_all_samples_norm_df$GeneName, EV_full_mean  = rowMeans(counts_all_samples_norm_df[1:3]))
EV_sphere_mean <- data.frame(GeneName= counts_all_samples_norm_df$GeneName, EV_sphere_mean  = rowMeans(counts_all_samples_norm_df[4:6]))
WT_full_mean <- data.frame(GeneName= counts_all_samples_norm_df$GeneName, WT_full_mean  = rowMeans(counts_all_samples_norm_df[7:9]))
WT_sphere_mean <- data.frame(GeneName= counts_all_samples_norm_df$GeneName, WT_sphere_mean  = rowMeans(counts_all_samples_norm_df[10:12]))
HEAA_full_mean <- data.frame(GeneName= counts_all_samples_norm_df$GeneName, HEAA_full_mean  = rowMeans(counts_all_samples_norm_df[13:15]))
HEAA_sphere_mean <- data.frame(GeneName= counts_all_samples_norm_df$GeneName, HEAA_sphere_mean  = rowMeans(counts_all_samples_norm_df[16:18]))

# merge was taking forever so I wanted to check that hte gnes were identical before just making new DF
identical(EV_full_mean$Gene, EV_sphere_mean$Gene, WT_full_mean$Gene, WT_sphere_mean$Gene, HEAA_full_mean$Gene, HEAA_sphere_mean$Gene)

counts_all_samples_norm_df <- cbind(EV_full_mean, 
                         WT_full = WT_full_mean$WT_full_mean,
                         HEAA_full = HEAA_full_mean$HEAA_full_mean,
                         EV_sphere = EV_sphere_mean$EV_sphere_mean,
                         WT_sphere = WT_sphere_mean$WT_sphere_mean,
                         HEAA_sphere = HEAA_sphere_mean$HEAA_sphere_mean)
colnames(counts_all_samples_norm_df)[2] <- "EV_full"


counts_norm_up_in_sphere <- counts_all_samples_norm_df[counts_all_samples_norm_df$GeneName %in% UPinSphere_AllEnhOverlap, ]
counts_norm_up_in_sphere <- counts_norm_up_in_sphere[!duplicated(counts_norm_up_in_sphere$GeneName),]
rownames(counts_norm_up_in_sphere) <- counts_norm_up_in_sphere$GeneName
counts_norm_up_in_sphere <- counts_norm_up_in_sphere[,-1]
counts_norm_up_in_sphere_mat <- as.matrix(counts_norm_up_in_sphere)
counts_norm_up_in_sphere_mat_log2 <- log2(counts_norm_up_in_sphere_mat)
counts_norm_up_in_sphere_mat_log2 <- na.omit(counts_norm_up_in_sphere_mat_log2)
counts_norm_up_in_sphere_mat_log2 <- counts_norm_up_in_sphere_mat_log2[is.finite(rowSums(counts_norm_up_in_sphere_mat_log2)),]

counts_norm_down_in_sphere <- counts_all_samples_norm_df[counts_all_samples_norm_df$GeneName %in% DOWNinSphere_AllEnhOverlap, ]
counts_norm_down_in_sphere <- counts_norm_down_in_sphere[!duplicated(counts_norm_down_in_sphere$GeneName),]
rownames(counts_norm_down_in_sphere) <- counts_norm_down_in_sphere$GeneName
counts_norm_down_in_sphere <- counts_norm_down_in_sphere[,-1]
counts_norm_down_in_sphere_mat <- as.matrix(counts_norm_down_in_sphere)
counts_norm_down_in_sphere_mat_log2 <- log2(counts_norm_down_in_sphere_mat)
counts_norm_down_in_sphere_mat_log2 <- na.omit(counts_norm_down_in_sphere_mat_log2)
counts_norm_down_in_sphere_mat_log2 <- counts_norm_down_in_sphere_mat_log2[is.finite(rowSums(counts_norm_down_in_sphere_mat_log2)),]

# plotting z-scores!

# up in sphere
library(tidyr)
counts_norm_up_in_sphere_mat_log2_scaled <- t(scale(t(counts_norm_up_in_sphere_mat_log2)))
counts_norm_up_in_sphere_mat_log2_scaled <- as.data.frame(counts_norm_up_in_sphere_mat_log2_scaled)
counts_norm_up_in_sphere_mat_log2_scaled$GeneName <- rownames(counts_norm_up_in_sphere_mat_log2_scaled)
counts_norm_up_in_sphere_mat_log2_scaled_long <- gather(counts_norm_up_in_sphere_mat_log2_scaled, key = sample, value = zscore, EV_full:HEAA_sphere )
counts_norm_up_in_sphere_mat_log2_scaled_long$sample <- ordered(counts_norm_up_in_sphere_mat_log2_scaled_long$sample,
                                                                levels = c("EV_full", "WT_full", "HEAA_full", "EV_sphere", "WT_sphere", "HEAA_sphere"))


library(ggplot2)
ggplot(counts_norm_up_in_sphere_mat_log2_scaled_long, aes(x = sample, y = zscore)) + geom_boxplot()
ggsave("ggplot_up_in_sphere_EVWTHEAAEnh_UTXmergedUnion_log2_zcore.pdf")


# down in sphere

counts_norm_down_in_sphere_mat_log2_scaled <- t(scale(t(counts_norm_down_in_sphere_mat_log2)))
counts_norm_down_in_sphere_mat_log2_scaled <- as.data.frame(counts_norm_down_in_sphere_mat_log2_scaled)
counts_norm_down_in_sphere_mat_log2_scaled$GeneName <- rownames(counts_norm_down_in_sphere_mat_log2_scaled)
counts_norm_down_in_sphere_mat_log2_scaled_long <- gather(counts_norm_down_in_sphere_mat_log2_scaled, key = sample, value = zscore, EV_full:HEAA_sphere )
counts_norm_down_in_sphere_mat_log2_scaled_long$sample <- ordered(counts_norm_down_in_sphere_mat_log2_scaled_long$sample,
                                                                levels = c("EV_full", "WT_full", "HEAA_full", "EV_sphere", "WT_sphere", "HEAA_sphere"))


ggplot(counts_norm_down_in_sphere_mat_log2_scaled_long, mapping = aes(x = sample, y = zscore, fill = sample)) + 
  geom_boxplot() + 
  theme_light() + 
  scale_fill_manual(values=c("#FF9999", "#3399FF")) + 
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(colour = "black", face = "bold")) + 
  xlab("") + 
  ylab("z-score of log2(normalized read count)") + 
  scale_fill_manual(values=c("#CCE5FF", "#0066CC", "#0066CC", "#FF9999", "#990000", "#990000")) 
ggsave("ggplot_down_in_sphere_EVWTHEAAEnh_UTXmergedUnion_log2_zcore.pdf", device = "pdf", height = 5, width = 6, useDingbats=FALSE)


# perform ttest for WT and HEAA sphere vs EV sphere

EV_sphere_sub <- counts_norm_down_in_sphere_mat_log2_scaled_long$zscore[counts_norm_down_in_sphere_mat_log2_scaled_long$sample == "EV_sphere"]
mean(EV_sphere_sub)

WT_sphere_sub <- counts_norm_down_in_sphere_mat_log2_scaled_long$zscore[counts_norm_down_in_sphere_mat_log2_scaled_long$sample == "WT_sphere"]
mean(WT_sphere_sub)

HEAA_sphere_sub <- counts_norm_down_in_sphere_mat_log2_scaled_long$zscore[counts_norm_down_in_sphere_mat_log2_scaled_long$sample == "HEAA_sphere"]
mean(HEAA_sphere_sub)

WT_vs_EV_sph <- t.test(EV_sphere_sub, WT_sphere_sub)
HEAA_vs_EV_sph <- t.test(EV_sphere_sub, HEAA_sphere_sub)

writeLines(con = "allDownGenes_sphere_ttest_pvalues_vsEVsphere.txt",
           text = c(capture.output(WT_vs_EV_sph),
                    capture.output(HEAA_vs_EV_sph)))

# perform wolcox rank sum for WT and HEAA sphere vs EV sphere


WT_vs_EV_sph <- wilcox.test(EV_sphere_sub, WT_sphere_sub)
HEAA_vs_EV_sph <- wilcox.test(EV_sphere_sub, HEAA_sphere_sub)

writeLines(con = "allDownGenes_sphere_wilcox_pvalues_vsEVsphere.txt",
           text = c(capture.output(WT_vs_EV_sph),
                    capture.output(HEAA_vs_EV_sph)))

writeLines(con = "Fig2B_UTX_EV_WT_andHEAA_enhancers_Gene_overlap_geneexpression_sessionInfo.txt", text = capture.output(sessionInfo()))

```


